<?php

namespace app\api\models;
use yii\base\Model;

class Login extends Model
{
    public $username;
    public $password;

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }
}